# Generated by Django 4.0.1 on 2022-01-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255)),
                ('sku_name', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('manufacturer_name', models.CharField(blank=True, max_length=255)),
                ('salt_name', models.CharField(blank=True, max_length=255)),
                ('drug_form', models.CharField(blank=True, max_length=255)),
                ('Pack_size', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=255)),
                ('product_banned_flag', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('price_per_unit', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
