# Generated by Django 4.0.1 on 2022-01-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NERapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedetails',
            name='id',
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='auto_increment_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
